sudo: true
os: trusty
distro: xenial
addons:
  chrome: stable
cache: false

before_install:
- google-chrome-stable --version
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
- sudo apt-get install chromium-browser -y
# Installing the Chrome Driver 71.0.3578.80
- wget http://chromedriver.storage.googleapis.com/71.0.3578.80/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip
- sudo mv chromedriver /usr/bin
# Issues with the Older Version of Pip,Installing Latest Version
- sudo python -m pip install --upgrade pip
- sudo pip install --upgrade --ignore-installed urllib3
- python --version
- sudo pip install selenium
# Checking the installed Packages
- whereis google-chrome-stable
- whereis chromedriver

script:
- python ./scripts/katalon_script.py
