sudo: true
os: trusty
distro: xenial
addons:
  chrome: stable
cache: false

before_install:
- google-chrome-stable --version
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
- sudo apt-get install chromium-browser -y
# Installing the Chrome Driver 71.0.3578.80
- wget http://chromedriver.storage.googleapis.com/71.0.3578.80/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip
- sudo mv chromedriver /usr/bin
- sudo pip install selenium

script:
- python ./scripts/TestSFDX.py
