sudo: true
os: trusty
distro: xenial
addons:
  chrome: stable
cache: false

before_install:
- chromium-browser -version | echo "Chromium Browser not installed"
- # start your web application and listen on `localhost`
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
- curl http://localhost:9222

script:
- python ./scripts/TestSFDX.py
